<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>AgentKit.Horde</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<Import Project="EpicGames.Horde.props" />
	<ItemGroup>
		<ProjectReference Include="..\AgentKit.Core\AgentKit.Core.csproj" />
		<ProjectReference Include="..\AgentKit.Vcs\AgentKit.Vcs.csproj" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="AgentKit.Horde.Tests" />
	</ItemGroup>
</Project>
