"""Hand-written one-line purposes for the modules agents most often need. Only modules present in the
scanned engine are listed in INDEX.md, so entries for modules that moved or were removed are harmless."""

CORE_MODULES = {
    # Foundations
    "Core": "Containers (TArray/TMap/TSet), FString/FName/FText, math, delegates, logging, HAL/platform layer, async/tasks, misc utilities, automation tests",
    "CoreUObject": "UObject system: UClass/FProperty reflection, GC, serialization, packages/linker loading, soft/weak pointers, FInstancedStruct (5.5+)",
    "TraceLog": "Low-level tracing for Unreal Insights (TRACE_CPUPROFILER_EVENT_SCOPE etc.)",
    "ApplicationCore": "Platform application, native windows, input message handling, cursor, clipboard",
    "Projects": "Plugin manager, .uplugin/.uproject descriptors, module loading policy",
    "Json": "FJsonObject/FJsonValue, JSON reader/writer",
    "JsonUtilities": "FJsonObjectConverter: UStruct <-> JSON",
    "DeveloperSettings": "UDeveloperSettings base for Project/Editor Settings pages",
    "Launch": "Engine entry point and main loop (FEngineLoop PreInit/Init/Tick)",
    "PakFile": "Pak/IoStore container mounting and reading",
    "AssetRegistry": "Asset metadata database: query assets without loading them",
    # Gameplay framework
    "Engine": "Gameplay framework (AActor, UActorComponent, UWorld, APawn, APlayerController, AGameModeBase), levels, world partition, subsystems, timers, materials/textures/meshes (game-thread side), networking/replication (UNetDriver, actor channels), physics glue",
    "InputCore": "FKey / EKeys key definitions",
    "EnhancedInput": "Input Actions, Input Mapping Contexts, modifiers, triggers",
    "GameplayTags": "FGameplayTag / FGameplayTagContainer and the tag manager",
    "GameplayTasks": "UGameplayTask and the tasks component (used by AI and GAS)",
    "GameplayAbilities": "Gameplay Ability System: abilities, effects, attribute sets, ability system component, cues",
    "AIModule": "AI controllers, behavior trees, blackboard, perception, EQS, crowd/path following",
    "NavigationSystem": "Navigation system, navmesh (Recast) generation and pathfinding queries",
    "StateTreeModule": "StateTree hierarchical state machine runtime",
    "SmartObjectsModule": "Smart Objects: claimable interaction points",
    "MassEntity": "Mass ECS: entities, fragments, processors",
    "ModularGameplay": "Game Feature components and extension handlers",
    "GameFeatures": "Game Feature plugins: runtime activation of feature plugins",
    "CommonUI": "Cross-platform UI framework on top of UMG: activatable widgets, input routing",
    "CommonInput": "Input-method detection and platform input metadata for CommonUI",
    "ModelViewViewModel": "UMG MVVM viewmodels and bindings",
    # Networking / online
    "NetCore": "Net serialization helpers, FFastArraySerializer support, net tokens",
    "IrisCore": "Iris replication system",
    "Sockets": "Socket subsystem abstraction",
    "Networking": "IP/UDP/TCP helpers built on Sockets",
    "HTTP": "HTTP requests (FHttpModule, IHttpRequest)",
    "OnlineSubsystem": "Legacy online services interfaces (sessions, identity, friends)",
    "OnlineServicesInterface": "Online Services (OSSv2) interfaces",
    # Rendering
    "RenderCore": "Render thread utilities, render resources, shader types/parameters, global shaders, RDG (RenderGraph)",
    "Renderer": "Scene renderer: deferred/mobile paths, lighting, shadows, Lumen, Nanite rendering, post-processing (mostly Private/)",
    "RHI": "Rendering Hardware Interface: GPU abstraction, resources, command lists",
    "RHICore": "Shared helpers for RHI backends",
    "D3D12RHI": "Direct3D 12 RHI backend",
    "VulkanRHI": "Vulkan RHI backend",
    "Landscape": "Landscape terrain actors, components, rendering and editing support",
    "Foliage": "Instanced foliage actors and types",
    "Niagara": "Niagara VFX runtime: systems, emitters, data interfaces",
    "MeshDescription": "Editable mesh representation used for import/build",
    "GeometryCore": "Geometry processing math: dynamic mesh, spatial structures",
    "ImageCore": "FImage and pixel-format conversion",
    "ImageWrapper": "PNG/JPEG/EXR/etc. encode/decode",
    # UI
    "SlateCore": "Slate foundations: SWidget, layout, painting, styles, input events",
    "Slate": "Standard Slate widgets and FSlateApplication",
    "UMG": "UUserWidget/UWidget UObject layer over Slate, widget blueprints runtime",
    # Animation / physics / audio / sequencer
    "AnimGraphRuntime": "Runtime animation nodes (FAnimNode_*), blend spaces, skeletal control",
    "AnimationCore": "Animation math helpers (two-bone IK, constraints)",
    "PhysicsCore": "Physics interface types shared by Chaos, physical materials, body setup",
    "Chaos": "Chaos physics solver: rigid bodies, collision, constraints, geometry collections",
    "ChaosVehicles": "Chaos vehicle movement",
    "AudioMixer": "Audio mixer, sources and submixes",
    "MetasoundEngine": "MetaSound assets and runtime",
    "MovieScene": "Sequencer runtime core: evaluation, tracks, sections, bindings",
    "MovieSceneTracks": "Built-in Sequencer track types (transform, property, audio...)",
    "LevelSequence": "Level Sequence assets and actors",
    "MediaAssets": "Media player, sources, textures",
    # Editor
    "UnrealEd": "Editor core: GEditor/UEditorEngine, transactions/undo, factories, importers, editor utilities",
    "EditorSubsystem": "UEditorSubsystem base",
    "LevelEditor": "Level editor module, viewports, toolbar extension points",
    "PropertyEditor": "Details panels: IDetailCustomization, IPropertyTypeCustomization",
    "ToolMenus": "UToolMenus: extensible editor menus and toolbars",
    "ContentBrowser": "Content Browser module and extension points",
    "AssetTools": "Asset type actions, asset creation/rename/import helpers",
    "BlueprintGraph": "K2 graph nodes (UK2Node_*) and Blueprint graph schema",
    "Kismet": "Blueprint editor",
    "KismetCompiler": "Blueprint compiler",
    "GraphEditor": "Generic graph editor widgets",
    "EditorScriptingUtilities": "Editor scripting helpers exposed to Blueprint/Python",
    "PythonScriptPlugin": "Editor Python integration",
    "Sequencer": "Sequencer editor",
    "InterchangeCore": "Interchange import framework core",
    # Testing / debugging
    "FunctionalTesting": "Functional test actors and helpers",
    "GameplayDebugger": "Gameplay debugger categories and replication",
}
